# Generated by Django 3.0.2 on 2020-01-30 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20200129_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 17, 28, 49, 244096, tzinfo=utc)),
        ),
    ]
